language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: 'ioet'
script:
  - npm test
  - npm run build
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
