export const TemplateAction = {
  ADD_TEMPLATES: 'TEMPLATE_ADD_TEMPLATES',
  ADD_TEMPLATE: 'TEMPLATE_ADD_TEMPLATE',
  ADD_EMPTY_ROW: 'ADD_EMPTY_ROW',
  REMOVE_EMPTY_ROW: 'REMOVE_EMPTY_ROW',
  EDIT_START: 'TEMPLATE_EDIT_START',
  EDIT_END: 'TEMPLATE_EDIT_END',
  EDIT_DATA: 'TEMPLATE_EDIT_DATA',
  UPDATE: 'TEMPLATE_UPDATE',
  REMOVE: 'TEMPLATE_REMOVE',
};

export const MessageAction = {
  SHOW_MESSAGE: 'SHOW_INFO_MESSAGE',
  HIDE_MESSAGE: 'HIDE_INFO_MESSAGE',
};

export const InitialAction = {
  INITIAL_STATE: '@@INIT',
};
